# Generated by Django 3.2.16 on 2023-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210902_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployinfo',
            name='depldescr',
            field=models.TextField(blank=True, null=True, verbose_name='参数描述'),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='deploypath',
            field=models.CharField(max_length=200, verbose_name='当前值'),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='prjalias',
            field=models.CharField(max_length=32, verbose_name='初始值'),
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='prjname',
            field=models.CharField(max_length=100, unique=True, verbose_name='参数名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='isenabled',
            field=models.BooleanField(default=True, verbose_name='项目状态'),
        ),
    ]
